#!/bin/sh
# Ensure that a simple mklabel command succeeds.
# Since there's no -s option, there are prompts.

# Copyright (C) 2007 Free Software Foundation, Inc.

# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
# 02110-1301, USA.

if test "$VERBOSE" = yes; then
  set -x
  parted --version
fi

. $srcdir/lang-default

pwd=`pwd`
t0=`echo "$0"|sed 's,.*/,,'`.tmp; tmp=$t0/$$
trap 'status=$?; cd "$pwd" && chmod -R u+rwx $t0 && rm -rf $t0 && exit $status' 0
trap '(exit $?); exit $?' 1 2 13 15

framework_failure=0
mkdir -p $tmp || framework_failure=1
cd $tmp || framework_failure=1

# create a file of size N bytes
N=1M
dev=loop-file
dd if=/dev/zero of=$dev bs=$N count=1 2> /dev/null || framework_failure=1
printf 'y\n\n' > in || framework_failure=1

if test $framework_failure = 1; then
  echo "$0: failure in testing framework" 1>&2
  (exit 1); exit 1
fi

fail=0
# First iteration works with no prompting, since there is no preexisting label.
parted $dev mklabel msdos > out 2>&1 || fail=1

# Now that there's a label, rerunning the same command is interactive.
parted ---pretend-input-tty $dev mklabel msdos < in > o2 2>&1 || fail=1
sed "s,^/.*$dev ,,;s, *,,;s, $,," o2 >> out

cat <<\EOF > exp || fail=1
WARNING: You are not superuser.  Watch out for permissions.
WARNING: You are not superuser.  Watch out for permissions.
Warning: The existing disk label on
will be destroyed and all
data on this disk will be lost. Do you want to continue?
Yes/No? y
New disk label type?  [msdos]?
EOF

cmp out exp || fail=1
test $fail = 1 && diff -u out exp 2> /dev/null

(exit $fail); exit $fail
