#!/bin/sh
# Ensure that mkpartfs fails when the device is too small.

# Copyright (C) 2007 Free Software Foundation, Inc.

# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
# 02110-1301, USA.

if test "$VERBOSE" = yes; then
  set -x
  parted --version
fi

. $srcdir/lang-default

pwd=`pwd`
t0=`echo "$0"|sed 's,.*/,,'`.tmp; tmp=$t0/$$
trap 'status=$?; cd "$pwd" && chmod -R u+rwx $t0 && rm -rf $t0 && exit $status' 0
trap '(exit $?); exit $?' 1 2 13 15

framework_failure=0
mkdir -p $tmp || framework_failure=1
cd $tmp || framework_failure=1

# You need much more than this to create a fat32 file system
N=1M
dev=loop-file
dd if=/dev/zero of=$dev bs=$N count=1 2> /dev/null || framework_failure=1
parted $dev mklabel msdos > /dev/null 2>&1 || framework_failure=1

cat <<\EOF > exp || framework_failure=1
WARNING: You are not superuser.  Watch out for permissions.
Error: Partition too big/small for a fat32 file system.
EOF

if test $framework_failure = 1; then
  echo "$0: failure in testing framework" 1>&2
  (exit 1); exit 1
fi

fail=0
# Require nonzero exit status.
parted -s $dev mkpartfs primary fat32 0 1 > out 2>&1 && fail=1

cmp out exp || fail=1
test $fail = 1 && diff -u out exp 2> /dev/null

(exit $fail); exit $fail
